# Form implementation generated from reading ui file 'project2.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from logic import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Time_zone_box = QtWidgets.QComboBox(parent=self.centralwidget)
        self.Time_zone_box.setGeometry(QtCore.QRect(30, 30, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Time_zone_box.setFont(font)
        self.Time_zone_box.setObjectName("Time_zone_box")
        self.Time_zone_box.addItem("")
        self.Time_zone_box.addItem("")
        self.Time_zone_box.addItem("")
        self.Time_zone_box.addItem("")
        self.Time_zone_box.addItem("")
        self.Time_zone_box.addItem("")
        self.time_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(260, 250, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setText(f"{get_time()}")
        self.time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.time_text_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.time_text_label.setGeometry(QtCore.QRect(260, 220, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.time_text_label.setFont(font)
        self.time_text_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_text_label.setObjectName("time_text_label")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 350, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project 2"))
        self.Time_zone_box.setItemText(0, _translate("MainWindow", "Hawaii Time"))
        self.Time_zone_box.setItemText(1, _translate("MainWindow", "Alaska Time"))
        self.Time_zone_box.setItemText(2, _translate("MainWindow", "Pacific Time"))
        self.Time_zone_box.setItemText(3, _translate("MainWindow", "Mountain Time"))
        self.Time_zone_box.setItemText(4, _translate("MainWindow", "Central Time"))
        self.Time_zone_box.setItemText(5, _translate("MainWindow", "Eastern Time"))
        self.time_text_label.setText(_translate("MainWindow", "The Time would be "))
        self.label.setText(_translate("MainWindow", "In ____ timezone."))





